GET http://localhost:5000/users

###
GET http://localhost:5000/users/1

###
POST  http://localhost:5000/users
Content-Type: application/json

{
    "name" : "FIKA",
    "email" : "taufika@gmail.com",
    "gender" : "perempuan"
}

###
PATCH   http://localhost:5000/users/11
Content-Type: application/json

{
    "name" : "Taufika",
    "email" : "taufika@gmail.com",
    "gender" : "perempuan"
}

###
DELETE  http://localhost:5000/users/11
